package `2024`.day08

import munit.FunSuite
import prelude.|>

val example =
  """|......#....#
     |...#....0...
     |....#0....#.
     |..#....0....
     |....0....#..
     |.#....A.....
     |...#........
     |#......#....
     |........A...
     |.........A..
     |..........#.
     |..........#.""".stripMargin |> Context.apply

class Part1Test extends FunSuite:
  test("two"):
    """|..........
       |...#......
       |..........
       |....a.....
       |..........
       |.....a....
       |..........
       |......#...
       |..........
       |..........""".stripMargin
      |> Context.apply |> (ctx => assertEquals(ctx.part1, 2))

  test("three"):
    """|..........
       |...#......
       |#.........
       |....a.....
       |........a.
       |.....a....
       |..#.......
       |......#...
       |..........
       |..........""".stripMargin
      |> Context.apply |> (ctx => assertEquals(ctx.part1, 4))

  test("example"):
    assertEquals(example.part1, 14)

class Part2Test extends FunSuite:
  test("T T T"):
    """|T....#....
       |...T......
       |.T....#...
       |.........#
       |..#.......
       |..........
       |...#......
       |..........
       |....#.....
       |..........""".stripMargin
      |> Context.apply |> (ctx => assertEquals(ctx.part2, 9))

  test("example"):
    assertEquals(example.part2, 34)
